# Generated by Django 3.2.4 on 2021-09-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
